version: '3'
services:

  nodejs:
    container_name: nodejs
    build: .
    volumes:
      - .:/usr/app/
      - .:/usr/app/node_modules/
    ports:
      - "8091:8091"
    restart: always
    depends_on:
      - nginx
    command: npm run serve -- --port 8091

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "10080:80"
      - "10443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    restart: always