version: '2.1'
services:

  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_DATABASE: motorcycle_info
      MYSQL_USER: demo
      MYSQL_PASSWORD: demo
    volumes:
      - /opt/bearings-info-db-container-data-persistence/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend-spring-boot-app:
    container_name: backend-spring-boot-app
    build:
      context: ./backend
    restart: on-failure
    links:
      - db:db
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8090:8090
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=demo
      - DATABASE_PASSWORD=demo
      - DATABASE_NAME=motorcycle_info
      - DATABASE_PORT=3306