version: '3'
services:

  mysql-server:
    container_name: mysql-server
    image: mysql:latest
    environment:
      MYSQL_DATABASE: motorcycle_info
      MYSQL_ROOT_PASSWORD: demo
      MYSQL_PASSWORD: demo
      MYSQL_ROOT_HOST: '%'
    ports:
      - 13306:3306
    restart: always
#
  backend-spring-boot-app:
    container_name: backend-spring-boot-app
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend-spring-boot-app:latest
    depends_on:
      - mysql-server
    restart: always
    expose:
      - "8080"
    environment:
      - DATABASE_HOST=mysql-server
      - DATABASE_USER=demo
      - DATABASE_PASSWORD=demo
      - DATABASE_NAME=motorcycle_info
      - DATABASE_PORT=3306

