version: '3'
services:
#  nginx:
#    container_name: some-nginx
#    image: nginx:1.13
#    restart: always
#    ports:
#      - 80:80
#      - 443:443
#    volumes:
#      - ./nginx/conf.d:/etc/nginx/conf.d
#    depends_on:
#      - app

  mysql-server:
    container_name: mysql-server
    image: mysql:latest
    environment:
      MYSQL_DATABASE: demo
      MYSQL_ROOT_PASSWORD: demo
      MYSQL_PASSWORD: demo
    ports:
      - 13306:3306
    restart: always

  backend-spring-boot-app:
    container_name: backend-spring-boot-app
    build:
      context: .
      dockerfile: Dockerfile
    image: backend-spring-boot-app:latest
    depends_on:
      - mysql-server
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=mysql-server
      - DATABASE_USER=demo
      - DATABASE_PASSWORD=demo
      - DATABASE_NAME=motorcycle_info
      - DATABASE_PORT=13306

